project:
  type: website
  output-dir: docs

website:
  title: "Castellar Granados"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full
    
resources:
  - publications.qmd

  
  
# ~ additional metadata excluded for brevity ~

