project:
  type: website
  output-dir: docs

website:
  title: "Castellar Granados"
  navbar:
    left:
      - href: index.qmd
        text: About
      - cv.qmd
      - publications.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

  
  
# ~ additional metadata excluded for brevity ~

