project:
  type: website
  output-dir: docs
editor: visual

website:
  title: "castegranados.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

  
  
# ~ additional metadata excluded for brevity ~

