---
title: "Publications"
format: html
---

**Peer-Reviewed Journal Articles**

Forthcoming. ”Race, Inequality, and Political Trust in Latin America” (with Francisco Sánchez). _Latin American Politics and Society_.

2024. ”Who Trusts Russia? Members of Parliament (MPs’) Support for Putin’s Government and Multilateralism” (with Francisco Sánchez). _Bulletin of Latin American Research_, Special
Issue.

2023. ”Institutionalization of Contentious Politics: Ecuador under Guillermo Lasso” (with Francisco Sánchez). _Revista de Ciencia Política (Santiago)_, 43(2), 279-300 [in Spanish].

2023. ”Between the Prairie, the Border, and the Port: Changes and Continuities in
Uruguayan Foreign Policy”. _UNISCI Journal_ 61, 89-109 [in Spanish].

2019. ”Do Parties Matter? Analysis of the Uruguayan Case”. _Comillas Journal of International Relations_ 15, 42-51 [in Spanish].

**Book Chapters**

2024. ”Las nubes pasan, Montevideo queda: los efectos de la pandemia y la alternancia
pol´ıtica en las elecciones departamentales y municipales 2020 en Uruguay”, in _Elecciones en América Latina: de pandemia y de derrotas (2020-2023)_, 695-730. Eds. M. Alc´antara, M. García Montero, and A. Bohigues. Madrid: Centro de Estudios Pol´ıticos y Constitucionales.

2023. ”Lengua y políticas de integración de inmigrantes en sociedades de acogida: dimensiones de análisis”, in _Políticas lingüísticas: avances, retrocesos y desafíos_, 29-37. Eds. C. Valero-Garcés, and N. Rodríguez Ortega. Malaga: Comares (with P.Biderbost, and G.Boscán).

2020. ”El protagonismo político de las mujeres inmigrantes en España. Identificación de casos emblemáticos”, in _Políticas públicas en defensa de la inclusión, la diversidad y el género_, 545-
560. Eds. R. Guzmán Ordaz, A. B. Nieto Libreo, and M. C. Gorjón Barranco. Salamanca: Ediciones Universidad de Salamanca (with P. Biderbost).

2020. ”Inmigración, políticas públicas y derechos humanos en América Latina. Detección de patrones a partir de la aplicación del índice MIPEX”, in _Derechos humanos y migraciones: una mirada interdisciplinaria_, 91-116. Ed. N. Sanz Mulas. Valencia: Tirant Lo Blanch (with
G. Boscán, and P. Biderbost).

2019. ”La dimensión de género en la integración política de inmigrantes”, in _Los derechos humanos 70 a˜nos después de la Declaración Universal_, 101-133. Ed. N. Sanz Mulas. Valencia: Tirant Lo Blanch (with P. Biderbost).

**Policy Papers and Essays**

2021. ”MIPEX 2020 y las pol´ıticas de integraci´on migrante en Am´erica Latina”. Barcelona: CIDOB.

2019. ”Adaptación al contexto latinoamericano del Migrant Integration Policy Index (MIPEX)”. Montevideo: Konrad Adenauer Stiftung.

**Book Reviews**

2022. Asbel Bohigues. "Elites, radicalismo y democracia. Un estudio comparado sobre ´
América Latina" (Madrid: Centro de Investigaciones Sociológicas; 2021), _Revista CIDOB d’Afers Internacionals_ 132: 235-237.

2019. Angel Arellano. "Nuevas campañas electorales en América Latina" (Montevideo: Konrad Adenauer Stiftung; 2019), _América Latina Hoy_ 82: 181-182.
